version:  '3.7'
services:
    mysql_db:
        image: mysql:8.0
        restart: on-failure
        command: --default-authentication-plugin=mysql_native_password --sql_mode=""
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql_db
        environment:
            PMA_HOST: mysql_db
            PMA_PORT: 3306
        ports:
            - '8080:80'

    nginx:
        image: nginx:1.15.3-alpine
        restart: on-failure
        volumes:
            - './public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        volumes:
            - './:/usr/src/app:cached'
        env_file:
            - .env
        user: '${LOCAL_USER}'