<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ063Ibx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ063Ibx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ063Ibx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ063Ibx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJ063Ibx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'J063Ibx',
    'container.build_id' => 'd0db251f',
    'container.build_time' => 1549468541,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ063Ibx');
